---
- name: Hosts do template
  hosts: 10.5.16.52
  gather_facts: no

  tasks: 
  - name: Efetiva permissao para Execucao
    file:
     path: /home/rodrigo/arquivo.arq
     owner: root
     group: root
     mode: u+x,g+x,o+x

  - name: Move arquivo de /home/rodrigo para /tmp
    command: mv /home/rodrigo/arquivo.arq /tmp/
