---
- name: Hosts do template
  hosts: 192.168.0.161
  gather_facts: no

  tasks: 
  - name: Efetiva permissao para Execucao
    file:
     path: /home/rodrigo/arquivo.arq
     owner: root
     group: root
     mode: u+x,g+x,o+x
    become: yes

  - name: Move arquivo de /home/rodrigo para /tmp
    command: mv /home/rodrigo/arquivo.arq /tmp/

  - name: Stop service sshd, in all cases
    service:
      name: sshd
      state: stop
